<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Route;

/**
 * Emits docs/STATUS.md.
 *
 * REPLACES THREE HAND-MAINTAINED DOCUMENTS that had all decayed into fiction:
 * KNOWN_LIMITATIONS.md still claimed there was no authorization layer (there is
 * one, with middleware and tests), that Laravel had never booted (167 tests
 * pass), and that 81 of 137 frontend endpoints were missing (the drift check
 * finds zero calls to endpoints that do not exist). Every one of those was true
 * when written and false by the time anyone read it.
 *
 * A status document a human maintains decays the moment someone forgets. A
 * generated one cannot, so this states only what it can measure and marks
 * everything else `unknown` rather than carrying a stale number forward. The
 * counts it cannot compute cheaply — test totals, the golden test's verdict —
 * are passed in by the CI job that just ran them, because a status file that
 * shells out to the test suite to describe the test suite is a recursion
 * waiting to time out.
 */
final class GenerateStatus extends Command
{
    protected $signature = 'brain:status
        {--tests=unknown : Total tests run}
        {--assertions=unknown : Total assertions}
        {--failures=unknown : Failing tests}
        {--golden=unknown : Golden intelligence-flow verdict (pass|fail)}
        {--drift=unknown : SPA calls to endpoints that do not exist}
        {--unverified=unknown : Operations with an underived schema}
        {--sha= : Commit SHA (defaults to git rev-parse HEAD)}
        {--out= : Output path (defaults to docs/STATUS.md)}';

    protected $description = 'Generate docs/STATUS.md from measurements rather than memory.';

    public function handle(): int
    {
        $routes = 0;
        $broken = 0;

        foreach (Route::getRoutes() as $route) {
            $action = $route->getActionName();

            if ($action === 'Closure' || ! str_contains($action, '@')) {
                continue;
            }

            $routes++;

            [$class, $method] = explode('@', $action, 2);

            if (! class_exists($class) || ! method_exists($class, $method)) {
                $broken++;
            }
        }

        $sha = (string) ($this->option('sha') ?: trim((string) @shell_exec('git rev-parse HEAD')));
        $sha = $sha === '' ? 'unknown' : substr($sha, 0, 40);

        $golden = (string) $this->option('golden');
        $verdict = match ($golden) {
            'pass' => 'THE LOOP TURNS',
            'fail' => '**THE LOOP DID NOT TURN**',
            default => 'unknown — the golden test was not run for this report',
        };

        $markdown = <<<MARKDOWN
        # Status

        <!--
          GENERATED by `php artisan brain:status`. DO NOT EDIT BY HAND.
          Every number here is measured, not remembered. A field reading
          `unknown` means it was not measured for this run — it never means
          zero, and it is never carried forward from a previous report.
        -->

        | Field | Value |
        |---|---|
        | Commit | `{$sha}` |
        | Generated | {$this->timestamp()} |
        | Golden intelligence flow | {$verdict} |
        | Tests | {$this->option('tests')} |
        | Assertions | {$this->option('assertions')} |
        | Failures | {$this->option('failures')} |
        | Routes declared | {$routes} |
        | Routes that do not resolve | {$broken} |
        | SPA calls to non-existent endpoints | {$this->option('drift')} |
        | Operations with an underived schema | {$this->option('unverified')} |

        ## What these mean

        **Golden intelligence flow** — `GoldenIntelligenceFlowTest` walks signal →
        evidence → reasoning → decision → execution → outcome → learning → memory
        through the real HTTP endpoints and the real consumer, and asserts the two
        honesty checkpoints FBR §3.5 requires (an honest UNKNOWN at step 4, an
        UNDETERMINED at step 7). If this reads "THE LOOP DID NOT TURN", do not
        deploy, whatever else is green.

        **Routes that do not resolve** — declared in `routes/api.php` with no public
        controller method behind them. This must be zero. It was not always: an
        approve endpoint was declared, absent, reported as a match by the old URL-
        matching audit, and fatal on first dispatch. `php artisan brain:check-routes`.

        **SPA calls to non-existent endpoints** — paths `web/src/api/*.ts` requests
        that the API does not expose. `npm run drift` in `contracts/` lists them.

        **Operations with an underived schema** — endpoints whose request or response
        shape `php artisan brain:openapi` could not derive from source, marked
        `x-unverified: true` in the OpenAPI document. They are honest gaps, not
        failures: an invented schema would pass CI and lie to every generated client.

        ## Not measured here

        Coverage, performance, and anything about the SPA's own test suite. If a
        number is not in the table above, this file makes no claim about it.
        MARKDOWN;

        $out = (string) ($this->option('out') ?: base_path('docs/STATUS.md'));

        if (! is_dir(dirname($out))) {
            mkdir(dirname($out), 0755, true);
        }

        file_put_contents($out, $markdown."\n");

        $this->info("brain:status: {$routes} routes, {$broken} broken -> {$out}");

        return $broken === 0 ? self::SUCCESS : self::FAILURE;
    }

    private function timestamp(): string
    {
        return now()->utc()->format('Y-m-d H:i:s').' UTC';
    }
}
