<?php

declare(strict_types=1);

/**
 * IMPORT PROFILES — the declarative contract between a workbook and the Brain.
 *
 * A profile is data, not code. Adding next quarter's FiberValley export, or a
 * whole new organization's workbooks, means editing this file — no new class,
 * no migration, no deploy of engine changes. That is the "reusable import
 * process" requirement, discharged.
 *
 * Profiles are keyed by ORGANIZATION SLUG, which matches the directory under
 * storage/imports/. `php artisan brain:import fibervalley` reads every profile
 * below and looks for its file in storage/imports/fibervalley/.
 *
 * ---------------------------------------------------------------------------
 * PROFILE KEYS
 * ---------------------------------------------------------------------------
 * file          Filename inside storage/imports/{org}/. Globs are allowed, so a
 *               file that gains a revision suffix next quarter still matches.
 * sheet         Sheet NAME, never index. Excel tab order and sheetN.xml
 *               numbering do not agree.
 * header_row    1-based row holding the column names. Three of the four
 *               FiberValley workbooks have a blank spacer row above the header,
 *               and 'Left ot Join' has two.
 * shape         'tabular'  — one record per row.
 *               'matrix'   — a pivot table: columns ARE entities. Unpivoted into
 *                            one record per (row-key, column) pair.
 * loader        'operational' — hpbrain_operational_records.
 *               'erp_roster'  — hrms_departments + tbluser (master data).
 * dataset       Value written to operational_records.dataset.
 * key           Column(s) forming the natural key. Several columns are joined
 *               with '|'. This is the idempotency contract: re-importing the
 *               same key updates rather than duplicates.
 * map           target_column => source header. Targets are the promoted
 *               columns on hpbrain_operational_records.
 * casts         target_column => 'datetime' | 'decimal' | 'int' | 'string'.
 *               Excel hands back date SERIALS (45777 = 2025-04-30), so any
 *               column that must land in a DATETIME needs an explicit cast.
 * derive        target_column => rule. Currently only 'closed_if_present:COL'.
 * payload       Source headers copied verbatim into the JSON payload column.
 * required      Source headers that must be non-empty; a row missing one is
 *               logged as an error row and skipped, never silently imported.
 * ---------------------------------------------------------------------------
 */
return [

    'fibervalley' => [

        /*
         | Field complaint tickets — 65,268 rows for FY 2025-26, one per ticket.
         | The operational heart of the dataset and the source of most signals.
         |
         | 'Final Solution' is blank on roughly two-thirds of rows. That is NOT
         | a mapping error and must not be defaulted: an unrecorded root cause
         | is a real, reportable gap, and the unresolved-root-cause rule exists
         | precisely to surface it. Defaulting it to 'Unknown' would erase the
         | finding.
         */
        'complaints' => [
            'file'       => 'Complain*.xlsx',
            'sheet'      => 'Data',
            'header_row' => 2,
            'shape'      => 'tabular',
            'loader'     => 'operational',
            'dataset'    => 'complaint',
            'key'        => ['Ticket'],
            'required'   => ['Ticket', 'GenerationDate'],
            'map' => [
                'occurred_at'     => 'GenerationDate',
                'closed_at'       => 'CloseDate',
                'category'        => 'Process Code',
                'sub_category'    => 'Final Solution',
                'owner_name'      => 'Engineer Name',
                'supervisor_name' => 'TL',
                'zone'            => 'zone',
                'area'            => 'Service Area',
                'subject_ref'     => 'UserId',
                'metric_value'    => 'Hours',
                'quantity'        => 'Complains more then 1 time',
            ],
            'casts' => [
                'occurred_at'  => 'datetime',
                'closed_at'    => 'datetime',
                'metric_value' => 'decimal',
                'quantity'     => 'int',
            ],
            'constants' => ['metric_unit' => 'hours'],
            'derive'    => ['status' => 'closed_if_present:CloseDate'],
            'payload'   => [
                'User Activation Date', 'Generated By', 'Solution Remark',
                'Commented By', 'Time Group', 'Month-YY', 'FY', 'Quarter',
                'Final POP L1', 'Final Junction Box L2', 'Complain in Single Month',
            ],
        ],

        /*
         | Provisioning job orders — 5,790 rows. 'Job Order' is unique; 'CRF
         | Number' is not (3 duplicates in the current export), which is why the
         | job order is the key.
         |
         | metric_value is Complete Days and quantity is Pending Days. Both are
         | days, so metric_unit says so — the same two columns mean hours for
         | complaints, and a rule that assumed hours everywhere would report a
         | 5-day install as 5 hours.
         */
        'work_orders' => [
            'file'       => 'Work Status*.xlsx',
            'sheet'      => 'Query Report',
            'header_row' => 2,
            'shape'      => 'tabular',
            'loader'     => 'operational',
            'dataset'    => 'work_order',
            'key'        => ['Job Order'],
            'required'   => ['Job Order'],
            'map' => [
                'occurred_at'     => 'Job Order Date',
                'closed_at'       => 'Reg Date',
                'status'          => 'Job Order Status',
                'category'        => 'Connection Type',
                'sub_category'    => 'Hold Status',
                'owner_name'      => 'Technician',
                'supervisor_name' => 'Assigned TL',
                'zone'            => 'Zone',
                'area'            => 'Ring',
                'subject_ref'     => 'User ID',
                'metric_value'    => 'Complete Days',
                'quantity'        => 'Pending Days',
            ],
            'casts' => [
                'occurred_at'  => 'datetime',
                'closed_at'    => 'datetime',
                'metric_value' => 'decimal',
                'quantity'     => 'int',
            ],
            'constants' => ['metric_unit' => 'days'],
            'payload'   => [
                'CRF Number', 'CRF Date', 'Plan Details', 'POP', 'Junction Box ',
                'Router', 'Router Status', 'JB Required', 'JB Status',
                'Sales Person / DSA', 'Feasibility', 'Mode of Connectivity',
                'Supplier', 'Cable Status', 'Cancelation Reason', 'Hold Group',
                'Last Hold Status', 'Remarks By TL', 'Month-YY', 'Fy', 'Ref Type',
            ],
        ],

        /*
         | Help-desk call volumes — one aggregate row per month, 12 rows total.
         | Every figure stays in payload: at 12 rows nothing needs an index, and
         | promoting one counter over the others would imply a hierarchy the
         | data does not have.
         */
        'helpdesk_monthly' => [
            'file'       => 'Help Desk Call Report.xlsx',
            'sheet'      => 'Data',
            'header_row' => 1,
            'shape'      => 'tabular',
            'loader'     => 'operational',
            'dataset'    => 'helpdesk_month',
            'key'        => ['Month-Yy'],
            'required'   => ['Month-Yy'],
            'map' => [
                'occurred_at'  => 'Date',
                'category'     => 'Quarter',
                'metric_value' => 'Total Calls(Total Answer+Total Drop)',
                'quantity'     => 'Persons',
            ],
            'casts' => [
                'occurred_at'  => 'datetime',
                'metric_value' => 'decimal',
                'quantity'     => 'int',
            ],
            'constants' => ['metric_unit' => 'calls'],
            'payload'   => ['Total Answers', 'Total Drop', 'Total Complains', 'Month', 'Year'],
        ],

        /*
         | Help-desk agent attendance — a pivot: dates down, 16 agent names
         | across. Unpivoted to one record per agent per day.
         |
         | A blank cell is NOT an absence. It means no submission was recorded,
         | and the sheet distinguishes that from an explicit 'Absent'. Blank
         | cells are skipped rather than imported as absent, because inventing
         | absences would slander named employees on the strength of a missing
         | form.
         */
        'helpdesk_attendance' => [
            'file'       => 'Help Desk Call Report.xlsx',
            'sheet'      => 'Attendance',
            'header_row' => 1,
            'shape'      => 'matrix',
            'loader'     => 'operational',
            'dataset'    => 'helpdesk_attendance',
            'matrix' => [
                'row_key'      => 'Row Labels',   // the date column
                'row_key_cast' => 'datetime',
                'entity_to'    => 'owner_name',   // each remaining header is an agent
                'value_to'     => 'status',
                'skip_blank'   => true,
            ],
            'constants' => ['area' => 'Help Desk'],
        ],

        /*
         | Field staff attendance — same pivot shape, ~80 technicians across,
         | 366 dates down, plus a per-row TL column carried onto every record.
         */
        'field_attendance' => [
            'file'       => 'CST Attendance Submission*.xlsx',
            'sheet'      => 'Attendance',
            'header_row' => 2,
            'shape'      => 'matrix',
            'loader'     => 'operational',
            'dataset'    => 'field_attendance',
            'matrix' => [
                'row_key'      => 'Date',
                'row_key_cast' => 'datetime',
                'entity_to'    => 'owner_name',
                'value_to'     => 'status',
                'skip_blank'   => true,
                // Columns that are context, not entities. Excluding them stops
                // "TL Name or Manager Name" being imported as a technician who
                // was marked present with the value of his own name.
                'carry' => ['supervisor_name' => 'TL Name or Manager Name'],
                'ignore' => ['Month'],
            ],
            'constants' => ['area' => 'Field'],
        ],

        /*
         | Staff roster — the ONLY master data in the four workbooks. Department,
         | employee name, reporting TL, and a True/False active flag per month.
         |
         | This one loads into the ERP tables (hrms_departments, tbluser) under
         | FiberValley's sub_institute_id, because that is where the Brain reads
         | Person and Department from for every organization. The payoff is that
         | the five existing SignalGenerator rules and the ERP tiles on the
         | Organization Intelligence Home light up for FiberValley with no new
         | code at all.
         */
        'staff_roster' => [
            'file'       => 'CST Attendance Submission*.xlsx',
            'sheet'      => 'Left ot Join',
            'header_row' => 3,
            'shape'      => 'tabular',
            'loader'     => 'erp_roster',
            'key'        => ['Employee Name'],
            'required'   => ['Employee Name'],
            'map' => [
                'full_name'  => 'Employee Name',
                'department' => 'Department',
                'manager'    => 'TL/Manager',
            ],
            // The twelve month flags decide whether the person is currently on
            // staff. The loader reads the LAST non-empty flag as current status.
            'active_flags' => [
                'Apr-2025', 'May-2025', 'Jun-2025', 'Jul-2025', 'Aug-2025', 'Sep-2025',
                'Oct-2025', 'Nov-2025', 'Dec-2025', 'Jan-2026', 'Feb-2026', 'Mar-2026',
            ],
        ],
    ],
];
